server:
  host: 127.0.0.1
  port: 8080
  mode: dev

log:
  level: debug
  logdir: ./logs
  filename: app.log
  console: true
  maxsize: 100
  maxbackups: 10
  maxage: 7
  compress: false

database:
  path: data/trail-vault.db
